"""added Game and Node

Revision ID: 938fa5175c9a
Revises: 
Create Date: 2020-02-01 10:13:32.442234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938fa5175c9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_name'), 'game', ['name'], unique=True)
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger', sa.String(length=64), nullable=True),
    sa.Column('is_head', sa.Boolean(), nullable=True),
    sa.Column('is_tail', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('is_head'),
    sa.UniqueConstraint('is_tail')
    )
    op.create_table('nodes',
    sa.Column('parent_node_id', sa.Integer(), nullable=True),
    sa.Column('child_node_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['parent_node_id'], ['node.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes')
    op.drop_table('node')
    op.drop_index(op.f('ix_game_name'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
